In [27]:
import casatools

In [35]:
import numpy as np

In [52]:
im = casatools.image()

In [53]:
im.open("UV-171060.4spw.cont.image.fits")

True

In [67]:
w = im.toworld(np.array([82.1, 95.9]), 'n')  # return world coordinate in radian

In [72]:
w_rad = w['numeric'][:2]

In [77]:
w_degree = w_rad*180/np.pi

In [38]:
from astropy import units as u
from astropy.coordinates import SkyCoord

In [40]:
c = SkyCoord(w[0]*u.degree, w[1]*u.degree)

In [41]:
c.ra.hms

hms_tuple(h=9.0, m=59.0, s=9.585421365011939)

In [47]:
c.dec.dms

dms_tuple(d=2.0, m=20.0, s=29.96000775258274)

In [81]:
p = im.topixel(w_rad)

In [82]:
p['numeric'][:2]

array([82.1, 95.9])

# Reading CRTF

In [83]:
import json

In [90]:
    def readCRTF (crtf):
        f = open(crtf, 'r+')
        output = f.readlines()
        aper = output[1]
        # x = np.array(json.loads(aper.replace(' ','').split('c')[0].replace('poly','').replace('pix','')))[:,0]
        # y = np.array(json.loads(aper.replace(' ','').split('c')[0].replace('poly','').replace('pix','')))[:,1]
        pixel_arr = np.array(json.loads(aper.replace(' ','').split('c')[0].replace('poly','').replace('pix','')))
        f.close()
        # return x, y
        return pixel_arr

In [91]:
pixel_arr = readCRTF('UV-171060_peri.crtf')

In [97]:
pixel_arr

array([[82.1, 95.9],
       [80. , 94.4],
       [81.2, 91.8],
       [81. , 89.5],
       [80.5, 86.1],
       [79. , 83.4],
       [79.6, 79.8],
       [83.9, 76.1],
       [85.8, 78.4],
       [85.3, 80.1],
       [83.2, 83. ],
       [93.1, 86.9],
       [94.7, 91. ],
       [93.4, 94.5],
       [91.7, 95. ],
       [90.2, 95. ],
       [86.4, 98.5],
       [84.5, 98.5],
       [82.8, 96.3]])

In [98]:
for pixel_coord in pixel_arr:
    print(pixel_coord)

[82.1 95.9]
[80.  94.4]
[81.2 91.8]
[81.  89.5]
[80.5 86.1]
[79.  83.4]
[79.6 79.8]
[83.9 76.1]
[85.8 78.4]
[85.3 80.1]
[83.2 83. ]
[93.1 86.9]
[94.7 91. ]
[93.4 94.5]
[91.7 95. ]
[90.2 95. ]
[86.4 98.5]
[84.5 98.5]
[82.8 96.3]


In [1]:
import adpipy

In [5]:
am = adpipy.AlmaMap('UV-171060.spw27.line.image.fits')

UV-171060.spw27.line.image.fits is a ALMA Data Cube
Image data is not 2-dimensional. Return None.


In [6]:
am.imgdata.shape

(1, 240, 180, 180)

In [7]:
am.imgdata

array([[[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan

In [1]:
import adpipy

In [2]:
help(adpipy)

Help on package adpipy:

NAME
    adpipy

PACKAGE CONTENTS
    AlmaMap
    DetectSources
    ExtractNSigmaRegions
    NoiseCal
    Photometry
    utils (package)

SUBMODULES
    crtftools
    plottools

FILE
    /Users/menorahlam/myvenv/lib/python3.8/site-packages/adpipy/__init__.py




In [4]:
help(adpipy.utils)

Help on package adpipy.utils in adpipy:

NAME
    adpipy.utils

PACKAGE CONTENTS
    crtftools
    plottools

FILE
    /Users/menorahlam/myvenv/lib/python3.8/site-packages/adpipy/utils/__init__.py


